#pragma once
#include <frc/geometry/Pose2d.h>
#include <frc/kinematics/ChassisSpeeds.h>
#include "maplesim/simulation/drivesims/configs/DriveTrainSimulationConfig.h"

class btCollisionShape;
struct btDefaultMotionState;
class btRigidBody;

namespace maplesim {

/**
 *
 *
 * <h1>Represents an Abstract Drivetrain Simulation.</h1>
 *
 * <h3>Simulates the Mass, Collision Space, and Friction of the Drivetrain.</h3>
 *
 * <p>This class models the physical properties of a drivetrain, including mass and collision space.
 *
 * <p>It also provides APIs to obtain the status (position, velocity etc.) in WPILib geometry classes.
 *
 * <p>The propelling forces generated by motors are simulated in its subclass, or {@link SwerveDriveSimulation}.
 */
class AbstractDriveTrainSimulation {
   public:
    static constexpr double BUMPER_COEFFICIENT_OF_FRICTION = 0.65;
    static constexpr double BUMPER_COEFFICIENT_OF_RESTITUTION = 0.08;

    /**
     *
     *
     * <h2>Sets the Robot's Current Pose in the Simulation World.</h2>
     *
     * <p>This method instantly teleports the robot to the specified pose in the simulation world. The robot does not
     * drive to the new pose; it is moved directly.
     *
     * @param robotPose the desired robot pose, represented as a {@link Pose2d}
     */
    void SetSimulationWorldPose(const frc::Pose2d& robotPose);

    /**
     *
     *
     * <h2>Sets the Robot's Speeds to the Given Chassis Speeds.</h2>
     *
     * <p>This method sets the robot's current velocity to the specified chassis speeds.
     *
     * <p>The robot does not accelerate smoothly to these speeds; instead, it jumps to the velocity
     * <strong>Instantaneously</strong>.
     *
     * @param givenSpeeds the desired chassis speeds, represented as a {@link ChassisSpeeds} object
     */
    void SetRobotSpeeds(const frc::ChassisSpeeds& givenSpeeds);

    /**
     *
     *
     * <h2>Abstract Simulation Sub-Tick Method.</h2>
     *
     * <p>This method is called every time the simulation world is updated.
     *
     * <p>It is implemented in the sub-classes of {@link AbstractDriveTrainSimulation}.
     *
     * <p>It is responsible for applying the propelling forces to the robot during each sub-tick of the simulation.
     */
    virtual void SimulationSubTick() = 0;

    /**
     *
     *
     * <h2>Gets the Actual Pose of the Drivetrain in the Simulation World.</h2>
     *
     * <p>This method is used to display the robot on <a
     * href="https://docs.advantagescope.org/tab-reference/3d-field/">AdvantageScope Field3d</a> or to <a
     * href="https://docs.photonvision.org/en/latest/docs/simulation/simulation-java.html#updating-the-simulation-world">update
     * vision simulations</a>.
     *
     * <p><strong>Note:</strong> Do not use this method to simulate odometry! For a more realistic odometry simulation,
     * use a {@link SwerveDriveSimulation} together with a
     * {@link edu.wpi.first.math.estimator.SwerveDrivePoseEstimator}.
     *
     * @return a {@link Pose2d} object yielding the current world pose of the robot in the simulation
     */
    frc::Pose2d GetSimulatedDriveTrainPose() const;

    /**
     *
     *
     * <h2>Gets the Actual Robot-Relative Chassis Speeds from the Simulation.</h2>
     *
     * <p>This method returns the actual chassis speeds of the drivetrain in the simulation, relative to the robot.
     *
     * <p>To simulate the chassis speeds calculated by encoders, use a {@link SwerveDriveSimulation} together with
     * {@link edu.wpi.first.math.kinematics.SwerveDriveKinematics#toChassisSpeeds(SwerveModuleState...)} for a more
     * realistic simulation.
     *
     * @return the actual chassis speeds in the simulation world, <strong>Robot-Relative</strong>
     */
    frc::ChassisSpeeds GetDriveTrainSimulatedChassisSpeedsRobotRelative() const;

    /**
     *
     *
     * <h2>Gets the Actual Field-Relative Chassis Speeds from the Simulation.</h2>
     *
     * <p>This method returns the actual chassis speeds of the drivetrain in the simulation, relative to the robot.
     *
     * <p>To simulate the chassis speeds calculated by encoders, use a {@link SwerveDriveSimulation} together with
     * {@link edu.wpi.first.math.kinematics.SwerveDriveKinematics#toChassisSpeeds(SwerveModuleState...)} for a more
     * realistic simulation.
     *
     * @return the actual chassis speeds in the simulation world, <strong>Field-Relative</strong>
     */
    frc::ChassisSpeeds GetDriveTrainSimulatedChassisSpeedsFieldRelative() const;

    DriveTrainSimulationConfig config;

   protected:
    AbstractDriveTrainSimulation(const DriveTrainSimulationConfig& config, const frc::Pose2d& initialPose);

   private:
    std::unique_ptr<btCollisionShape> shape;
    std::unique_ptr<btDefaultMotionState> motionState;
    std::unique_ptr<btRigidBody> body;
};

}  // namespace maplesim
