#pragma once
#include <deque>
#include <frc/kinematics/SwerveModuleState.h>
#include "maplesim/motorsims/MapleMotorSim.h"
#include "maplesim/simulation/drivesims/configs/SwerveModuleSimulationConfig.h"

namespace maplesim {

/**
 *
 *
 * <h2>Simulation for a Single Swerve Module.</h2>
 *
 * <p>Check <a href='https://shenzhen-robotics-alliance.github.io/maple-sim/swerve-sim-hardware-abstraction/'>Online
 * Documentation</a>
 *
 * <p>This class provides a simulation for a single swerve module in the {@link SwerveDriveSimulation}.
 *
 * <h3>1. Purpose</h3>
 *
 * <p>This class serves as the bridge between your code and the physics engine.
 *
 * <p>You will apply voltage outputs to the drive/steer motor of the module and obtain their encoder readings in your
 * code, just as how you deal with your physical motors.
 *
 * <h3>2. Perspectives</h3>
 *
 * <ul>
 *   <li>Simulates the steering mechanism using a custom brushless motor simulator.
 *   <li>Simulates the propelling force generated by the driving motor, with a current limit.
 *   <li>Simulates encoder readings, which can be used to simulate a {@link SwerveDriveOdometry}.
 * </ul>
 *
 * <h3>3. Simulating Odometry</h3>
 *
 * <ul>
 *   <li>Retrieve the encoder readings from {@link #getDriveEncoderUnGearedPosition()}} and
 *       {@link #getSteerAbsoluteFacing()}.
 *   <li>Use {@link SwerveDriveOdometry} to estimate the pose of your robot.
 *   <li><a
 *       href="https://v6.docs.ctr-electronics.com/en/latest/docs/application-notes/update-frequency-impact.html">250Hz
 *       Odometry</a> is supported. You can retrive cached encoder readings from every sub-tick through
 *       {@link #getCachedDriveEncoderUnGearedPositions()} and {@link #getCachedSteerAbsolutePositions()}.
 * </ul>
 *
 * <p>An example of how to simulate odometry using this class is the <a
 * href='https://github.com/Shenzhen-Robotics-Alliance/maple-sim/blob/main/templates/AdvantageKit_AdvancedSwerveDriveProject/src/main/java/frc/robot/subsystems/drive/ModuleIOSim.java'>ModuleIOSim.java</a>
 * from the <code>Advanced Swerve Drive with maple-sim</code> example.
 */
class SwerveModuleSimulation {
   public:
    /**
     *
     *
     * <h2>Constructs a Swerve Module Simulation.</h2>
     *
     * <p>If you are using {@link SimulatedArena#overrideSimulationTimings(Time, int)} to use custom timings, you must
     * call the method before constructing any swerve module simulations using this constructor.
     *
     * @param config the configuration
     */
    SwerveModuleSimulation(SwerveModuleSimulationConfig config);

    constexpr const SimMotorConfigs& GetDriveMotorConfigs() const { return config.driveMotorConfigs; }

    constexpr const SimMotorConfigs& GetSteerMotorConfigs() const { return config.steerMotorConfigs; }

    /**
     *
     *
     * <h2>Sets the motor controller for the drive motor.</h2>
     *
     * <p>The configured controller runs control loop on the motor.
     *
     * @param driveMotorController the motor controller to control the drive motor
     */
    template <typename T>
    inline T& UseDriveMotorController(std::unique_ptr<T> driveMotorController) {
        this->driveMotorController = std::move(driveMotorController);
        return *driveMotorController;
    }

    inline GenericMotorController& UseGenericMotorControllerForDrive() {
        return UseDriveMotorController(std::make_unique<GenericMotorController>(config.driveMotorConfigs.motor));
    }

    /**
     *
     *
     * <h2>Requests the Steering Motor to Run at a Specified Output.</h2>
     *
     * <p>Think of it as the <code>requestOutput()</code> of your physical steering motor.
     *
     * @param steerMotorController the motor controller to control the steer motor
     */
    template <typename T>
    inline T& UseSteerMotorController(std::unique_ptr<T> steerMotorController) {
        return steerMotorSim.UseMotorController(steerMotorController);
    }

    inline GenericMotorController& UseGenericControllerForSteer() { return steerMotorSim.UseSimpleDCMotorController(); }

    /**
     *
     *
     * <h2>Updates the Simulation for This Module.</h2>
     *
     * <p><strong>Note:</strong> Friction forces are not simulated in this method.
     *
     * @param moduleCurrentGroundVelocityWorldRelative the current ground velocity of the module, relative to the world
     * @param robotFacing the absolute facing of the robot, relative to the world
     * @param gravityForceOnModuleNewtons the gravitational force acting on this module, in newtons
     * @return the propelling force generated by the module, as a {@link Vector2} object
     */
    Eigen::Vector2d UpdateSimulationSubTickGetModuleForce(Eigen::Vector2d moduleCurrentGroundVelocityWorldRelative,
                                                          frc::Rotation2d robotFacing, units::newton_t gravityForceOnModule);

    /**
     *
     *
     * <h2>Calculates the amount of propelling force that the module generates.</h2>
     *
     * <p>For most of the time, that propelling force is directly applied to the drivetrain. And the drive wheel runs as
     * fast as the ground velocity
     *
     * <p>However, if the propelling force exceeds the gripping, only the max gripping force is applied. The rest of the
     * propelling force will cause the wheel to start skidding and make the odometry inaccurate.
     *
     * @param grippingForceNewtons the amount of gripping force that wheel can generate, in newtons
     * @param moduleWorldFacing the current world facing of the module
     * @param moduleCurrentGroundVelocity the current ground velocity of the module, world-reference
     * @return a vector representing the propelling force that the module generates, world-reference
     */
    Eigen::Vector2d GetPropellingForce(units::newton_t grippingForce, frc::Rotation2d moduleWorldFacing,
                                       Eigen::Vector2d moduleCurrentGroundVelocity);

    /**
     *
     *
     * <h2>Calculates the amount of torque that the drive motor can generate on the wheel.</h2>
     *
     * @return the amount of torque on the wheel by the drive motor, in Newton * Meters
     */
    units::newton_meter_t GetDriveWheelTorque();

    /** @return the current module state of this simulation module */
    constexpr frc::SwerveModuleState GetCurrentState() const {
        return frc::SwerveModuleState{GetDriveWheelFinalSpeed() * config.WHEEL_RADIUS / 1_tr, GetSteerAbsoluteFacing()};
    }

    /**
     *
     *
     * <h2>Obtains the Actual Output Voltage of the Drive Motor.</h2>
     *
     * @return the actual output voltage of the drive motor
     */
    constexpr units::volt_t GetDriveMotorAppliedVoltage() const { return driveMotorAppliedVoltage; }

    /**
     *
     *
     * <h2>Obtains the Actual Output Voltage of the Steering Motor.</h2>
     *
     * @return the actual output voltage of the steering motor
     * @see MapleMotorSim#getAppliedVoltage()
     */
    constexpr units::volt_t GetSteerMotorAppliedVoltage() const { return steerMotorSim.GetAppliedVoltage(); }

    /**
     *
     *
     * <h2>Obtains the Amount of Current Supplied to the Drive Motor.</h2>
     *
     * @return the current supplied to the drive motor
     */
    inline units::ampere_t GetDriveMotorSupplyCurrent() const {
        return GetDriveMotorStatorCurrent() * driveMotorAppliedVoltage / SimulatedBattery::GetBatteryVoltage();
    }

    /**
     *
     *
     * <h2>Obtains the Stator current the Drive Motor.</h2>
     *
     * @return the stator current of the drive motor
     */
    constexpr units::ampere_t GetDriveMotorStatorCurrent() const { return driveMotorStatorCurrent; }

    /**
     *
     *
     * <h2>Obtains the Amount of Current Supplied to the Steer Motor.</h2>
     *
     * @return the current supplied to the steer motor
     * @see MapleMotorSim#getSupplyCurrent()
     */
    inline units::ampere_t GetSteerMotorSupplyCurrent() const { return steerMotorSim.GetSupplyCurrent(); }

    /**
     *
     *
     * <h2>Obtains the Stator current the Steer Motor.</h2>
     *
     * @return the stator current of the drive motor
     * @see MapleMotorSim#getSupplyCurrent()
     */
    constexpr units::ampere_t GetSteerMotorStatorCurrent() const { return steerMotorSim.GetStatorCurrent(); }

    /**
     *
     *
     * <h2>Obtains the Position of the Drive Encoder.</h2>
     *
     * <p>This value represents the un-geared position of the encoder, i.e., the amount of radians the drive motor's
     * encoder has rotated.
     *
     * @return the position of the drive motor's encoder (un-geared)
     */
    constexpr units::radian_t GetDriveEncoderUnGearedPosition() const { return GetDriveWheelFinalPosition() * config.DRIVE_GEAR_RATIO; }

    /**
     *
     *
     * <h2>Obtains the Final Position of the Wheel.</h2>
     *
     * <p>This method provides the final position of the drive encoder in terms of wheel angle.
     *
     * @return the final position of the drive encoder (wheel rotations)
     */
    constexpr units::radian_t GetDriveWheelFinalPosition() const { return driveWheelFinalPosition; }

    /**
     *
     *
     * <h2>Obtains the Speed of the Drive Encoder.</h2>
     *
     * @return the un-geared speed of the drive encoder
     */
    constexpr units::radians_per_second_t GetDriveEncoderUnGearedSpeed() const {
        return GetDriveWheelFinalSpeed() * config.DRIVE_GEAR_RATIO;
    }

    /**
     *
     *
     * <h2>Obtains the Final Speed of the Wheel.</h2>
     *
     * @return the final speed of the drive wheel
     */
    constexpr units::radians_per_second_t GetDriveWheelFinalSpeed() const { return driveWheelFinalSpeed; }

    /**
     *
     *
     * <h2>Obtains the Relative Position of the Steer Encoder.</h2>
     *
     * @return the relative encoder position of the steer motor
     * @see MapleMotorSim#getEncoderPosition()
     */
    constexpr units::radian_t GetSteerRelativeEncoderPosition() const {
        return GetSteerAbsoluteFacing().Radians() * config.STEER_GEAR_RATIO + steerRelativeEncoderOffset;
    }

    /**
     *
     *
     * <h2>Obtains the Speed of the Steer Relative Encoder (Geared).</h2>
     *
     * @return the speed of the steer relative encoder
     * @see MapleMotorSim#getEncoderVelocity()
     */
    constexpr units::radians_per_second_t GetSteerRelativeEncoderVelocity() const {
        return GetSteerAbsoluteEncoderSpeed() * config.STEER_GEAR_RATIO;
    }

    /**
     *
     *
     * <h2>Obtains the Absolute Facing of the Steer Mechanism.</h2>
     *
     * @return the absolute facing of the steer mechanism, as a {@link Rotation2d}
     */
    constexpr frc::Rotation2d GetSteerAbsoluteFacing() const { return frc::Rotation2d{GetSteerAbsoluteAngle()}; }

    /**
     *
     *
     * <h2>Obtains the Absolute Angle of the Steer Mechanism.</h2>
     *
     * @return the (continuous) final angle of the steer mechanism, as a {@link Angle}
     * @see MapleMotorSim#getAngularPosition()
     */
    constexpr units::radian_t GetSteerAbsoluteAngle() const { return steerMotorSim.GetAngularPosition(); }

    /**
     *
     *
     * <h2>Obtains the Absolute Rotational Velocity of the Steer Mechanism.</h2>
     *
     * @return the absolute angular velocity of the steer mechanism
     */
    constexpr units::radians_per_second_t GetSteerAbsoluteEncoderSpeed() const { return steerMotorSim.GetVelocity(); }

    /**
     *
     *
     * <h2>Obtains the Cached Readings of the Drive Encoder's Un-Geared Position.</h2>
     *
     * <p>The values of {@link #getDriveEncoderUnGearedPosition()} are cached at each sub-tick and can be retrieved
     * using this method.
     *
     * @return an array of cached drive encoder un-geared positions
     */
    std::vector<units::radian_t> GetCachedDriveEncoderUnGearedPositions() const;

    /**
     *
     *
     * <h2>Obtains the Cached Readings of the Drive Encoder's Final Position (Wheel Rotations).</h2>
     *
     * <p>The values of {@link #getDriveWheelFinalPosition()} are cached at each sub-tick and are divided by the gear
     * ratio to obtain the final wheel rotations.
     *
     * @return an array of cached drive encoder final positions (wheel rotations)
     */
    inline std::vector<units::radian_t> GetCachedDriveWheelFinalPositions() const {
        return std::vector<units::radian_t>{driveWheelFinalPositionCache.begin(), driveWheelFinalPositionCache.end()};
    }

    /**
     *
     *
     * <h2>Obtains the Cached Readings of the Steer Relative Encoder's Position.</h2>
     *
     * <p>The values of {@link #getSteerRelativeEncoderPosition()} are cached at each sub-tick and can be retrieved
     * using this method.
     *
     * @return an array of cached steer relative encoder positions
     */
    std::vector<units::radian_t> GetCachedSteerRelativeEncoderPositions() const;

    /**
     *
     *
     * <h2>Obtains the Cached Readings of the Steer Absolute Positions.</h2>
     *
     * <p>The values of {@link #getSteerAbsoluteFacing()} are cached at each sub-tick and can be retrieved using this
     * method.
     *
     * @return an array of cached absolute steer positions, as {@link Rotation2d} objects
     */
    inline std::vector<frc::Rotation2d> GetCachedSteerAbsolutePositions() const {
        return std::vector<frc::Rotation2d>{steerAbsolutePositionCache.begin(), steerAbsolutePositionCache.end()};
    }

    /**
     *
     *
     * <h2>Obtains the "free spin" state of the module</h2>
     *
     * <p>The "free spin" state of a simulated module refers to its state after spinning freely for a long time under
     * the current input voltage
     *
     * @return the free spinning module state
     */
    constexpr frc::SwerveModuleState GetFreeSpinState() const {
        return frc::SwerveModuleState{
            config.driveMotorConfigs.CalculateMechanismVelocity(
                config.driveMotorConfigs.CalculateCurrent(config.driveMotorConfigs.friction), driveMotorAppliedVoltage) *
                config.WHEEL_RADIUS / 1_rad,
            GetSteerAbsoluteFacing()};
    }

    SwerveModuleSimulationConfig config;

   private:
    /**
     *
     *
     * <h2>Cache the encoder values for high-frequency odometry.</h2>
     *
     * <p>An internal method to cache the encoder values to their queues.
     */
    void UpdateEncoderCaches();

    MapleMotorSim steerMotorSim{config.steerMotorConfigs};

    units::volt_t driveMotorAppliedVoltage;
    units::ampere_t driveMotorStatorCurrent;
    units::radian_t driveWheelFinalPosition;
    units::radians_per_second_t driveWheelFinalSpeed;

    std::unique_ptr<SimulatedMotorController> driveMotorController =
        std::make_unique<GenericMotorController>(config.driveMotorConfigs.motor);

    // TODO: Make random
    units::radian_t steerRelativeEncoderOffset = 0_rad;
    std::deque<units::radian_t> driveWheelFinalPositionCache;
    std::deque<frc::Rotation2d> steerAbsolutePositionCache;
};

}  // namespace maplesim
